// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwHmTjg_rT-bU0NL1c71f5qkonf7H7eNM',
    appId: '1:214577366989:web:60a23440fb34ed74f52684',
    messagingSenderId: '214577366989',
    projectId: 'furryfriendsanimalclinic-13da3',
    authDomain: 'furryfriendsanimalclinic-13da3.firebaseapp.com',
    storageBucket: 'furryfriendsanimalclinic-13da3.firebasestorage.app',
    measurementId: 'G-PZPEFBSV25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCrEy2c8U4MBbdXr40lYyD0Lh_VT7_AQI',
    appId: '1:214577366989:android:e85a9c0d946a089ff52684',
    messagingSenderId: '214577366989',
    projectId: 'furryfriendsanimalclinic-13da3',
    storageBucket: 'furryfriendsanimalclinic-13da3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYAX12sBWr3dhwZsfmpgytQvC0kwWxSoY',
    appId: '1:214577366989:ios:22f6411ab20e1289f52684',
    messagingSenderId: '214577366989',
    projectId: 'furryfriendsanimalclinic-13da3',
    storageBucket: 'furryfriendsanimalclinic-13da3.firebasestorage.app',
    iosBundleId: 'com.example.furryFriendsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYAX12sBWr3dhwZsfmpgytQvC0kwWxSoY',
    appId: '1:214577366989:ios:22f6411ab20e1289f52684',
    messagingSenderId: '214577366989',
    projectId: 'furryfriendsanimalclinic-13da3',
    storageBucket: 'furryfriendsanimalclinic-13da3.firebasestorage.app',
    iosBundleId: 'com.example.furryFriendsAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwHmTjg_rT-bU0NL1c71f5qkonf7H7eNM',
    appId: '1:214577366989:web:b86028a2245ed78af52684',
    messagingSenderId: '214577366989',
    projectId: 'furryfriendsanimalclinic-13da3',
    authDomain: 'furryfriendsanimalclinic-13da3.firebaseapp.com',
    storageBucket: 'furryfriendsanimalclinic-13da3.firebasestorage.app',
    measurementId: 'G-T4WY02G4NH',
  );
}
